version: 0.1.x-{build}
image: Visual Studio 2022
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: ''
  package_version: 0.1.0.2-build{build}
  assembly_version: ''
  file_version: ''
environment:
  WEBHOOK_URL:
    secure: p3nnkhnWtqFFH8UJ1eaKFfRjFPlOVhNtmLjd94R7+KRlQRoRpjxUisauQsXm73lXVofTWfZh7BwzfYPIFG76BMIGLb/NwlZ/xCuiFOO9avEt6Ev/LwDBNBadz1H4/v8qNy+jZK1jpOCLrFZ2vnxDSPiQ9nIrUcwXR5TgQf7ABYs=
before_build:
- cmd: nuget restore "%APPVEYOR_BUILD_FOLDER%\ShoutStats.sln"
build:
  verbosity: minimal
after_build:
- cmd: >-
    7z a devbuild.zip "%APPVEYOR_BUILD_FOLDER%\ShoutStats.Core\bin\Debug\"

    7z a devbuild-console.zip "%APPVEYOR_BUILD_FOLDER%\ShoutStats.Console\bin\Debug\"

    7z a devbuild-ui.zip "%APPVEYOR_BUILD_FOLDER%\ShoutStats.WindowsUI\bin\Debug\"
artifacts:
- path: devbuild.zip
  name: Development build of ShoutStats
- path: devbuild-console.zip
  name: Development build of ShoutStats - Console test app
- path: devbuild-ui.zip
  name: Development build of ShoutStats - Windows UI test app
- path: ShoutStats.Core\bin\Debug\ShoutStats.Core.*.nupkg
deploy:
- provider: NuGet
  server: https://www.nuget.org/api/v2/package
  api_key:
    secure: 2ocxItByklPOySTf0USeSC6NpQGHHkhYMzj08PlSKNZE/VxLSLzcQpdt4VMTQnJI
  symbol_server: https://www.nuget.org/api/v2/package
on_success:
- ps: >-
    Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1

    ./send.ps1 success $env:WEBHOOK_URL
on_failure:
- ps: >-
    Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1

    ./send.ps1 failure $env:WEBHOOK_URL